# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-04-19 18:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Edeka',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=20)),
                ('brand', models.CharField(max_length=100)),
                ('weight', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('manufacture', models.CharField(blank=True, max_length=255, null=True)),
                ('ingredient', models.CharField(blank=True, max_length=500, null=True)),
                ('allergens', models.CharField(blank=True, max_length=500, null=True)),
                ('additives', models.CharField(blank=True, max_length=500, null=True)),
                ('nutrients', models.CharField(blank=True, max_length=1000, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
