# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-04-21 17:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20170420_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edeka',
            name='additives',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='edeka',
            name='allergens',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='edeka',
            name='description',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='edeka',
            name='image_path',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='edeka',
            name='ingredient',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='edeka',
            name='nutrients',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
