# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-04-21 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20170421_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edeka',
            name='additives',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='edeka',
            name='allergens',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='edeka',
            name='ingredient',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='edeka',
            name='manufacture',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='edeka',
            name='nutrients',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
